### ISSUE TITLE
Respect .env.development overrides

### ISSUE THREAD

**Issue by kratam** [nhost/nhost.toml#1]
Right now the only way to differentiate the prod and dev is to use `.secrets`. But there are use cases where I want to override or add env vars only in the dev setup, e.g. I want to have different values for `NODE_ENV`.

I also have flags (env vars) to skip updating a remote API in dev. If the flag is truthy I don't run the update logic in that function. These flags are not required in prod so creating a secret for them is not necessary.

**Comment by dbarrosop** [comment]
Ok, my suggestion would be as follows:

1. All env vars are required in the configuration file, this is a compromise to ensure environments are consistent.
2. However, instead of requiring a secret for everything we could allow overriding values locally with the `.env.development`

For instnace:

``` toml
# config.toml
[[ global.environment ]]
NODE_ENV='prod'
```

```
# .env.development
NODE_ENV=dev
```

For env vars that are not required in prod the solution would be to keep them empty:


``` toml
[[ global.environment ]]
SOME_ENV_I_DONT_USE_IN_PROD=''
```

```
# .env.development
SOME_ENV_I_DONT_USE_IN_PROD='this-is-dev'
```

I understand the second might not be ideal in some cases but it is mostly a compromise as we try to make sure people configures the environment correctly (currently, it is a common mistake that people define env vars locally but forgets to set them in the cloud so we are trying to help with that)

**Comment by kratam** [comment]
Another solution would be to introduce `development` into `nhost.toml`, e.g.:
```
[development]
[[development.environment]]
name = 'NODE_ENV'
value = 'development'
```

This might be better because these values are not secrets (if they were, they would be in `.secrets`) and we would be able to see everything in one file and push to git. The naming clearly states these are development env vars, but for another safety belt, the cli can warn if there are env vars added to `development` but not to `global`.

**Comment by kratam** [comment]
Related: I encountered an error a few months ago when my functions failed to deploy. It turned out there is a limit in the total length of the env vars (names + values) enforced by AWS. It worked locally but failed in the cloud because the deployment process added some internal env vars there.
Since then I'm trying not to put everything into the env vars.
